### ISSUE TITLE
Cannot write dataframe to cloudBigTable using PySpark Connector

### ISSUE THREAD

**Issue by sureshgv** [GoogleCloudDataproc/spark-bigtable-connector#8]
Hello, 

I followed the spark connector document https://github.com/GoogleCloudDataproc/spark-bigtable-connector

and getting error while writing to bigtable using spark.

spark.version = 3.5.1
Scala code runner version 2.12.18
bigtable_spark_connector_jar="gs://spark-lib/bigtable/spark-bigtable_2.12-0.1.0.jar"

spark = SparkSession.builder \
 .appName('df-to-bigtable')\
 .config("spark.jars", bigtable_spark_connector_jar) \
 .config("spark.jars.packages", "org.slf4j:slf4j-reload4j:1.7.36") \
 .getOrCreate()

Writing to bigtable:

df.repartition(10) \
 .write \
 .format("bigtable") \
 .options(catalog=catalog) \
 .option("spark.bigtable.project.id", bigtable_project_id) \
 .option("spark.bigtable.instance.id", bigtable_instance_id) \
 .option("spark.bigtable.create.new.table", create_new_table) \
 .save()

I am getting error:

Py4JJavaError: An error occurred while calling o338.save.

: org.apache.spark.SparkClassNotFoundException: [DATA_SOURCE_NOT_FOUND] Failed to find the data source: bigtable. Please find packages at `https://spark.apache.org/third-party-projects.html`.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.dataSourceNotFoundError(QueryExecutionErrors.scala:724)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:647)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:697)
	at org.apache.spark.sql.DataFrameWriter.lookupV2Provider(DataFrameWriter.scala:863)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:257)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:248)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: bigtable.DefaultSource
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:633)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:633)
	at scala.util.Failure.orElse(Try.scala:224)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:633)
	... 16 more

**Comment by davidrabinowitz** [comment]
Is spark run locally or on Dataproc? Is it an application or a notebook?

**Comment by sureshgv** [comment]
It runs on a dataproc in a notebook.

**Comment by rkaregar** [comment]
Thanks for the information, can you share the Dataproc version as well as the command you're using to create the cluster, so we can attempt reproducing the issue?

Are you following the example [here](https://github.com/GoogleCloudDataproc/spark-bigtable-connector/blob/main/examples/notebooks/PySpark%20with%20Bigtable%20Time-Series%20Example.ipynb)?

If possible, you could try the PySpark example (without notebook) from [here](https://github.com/GoogleCloudDataproc/spark-bigtable-connector/tree/main/examples/python) as well, so we can isolate whether it's a cluster-related issue or notebook-related issue.

**Comment by davidrabinowitz** [comment]
Is it a PySpark notebook or a Python one? In PySpark notebook the SparkSession is created for you beforehand, so you cannot add any additional libraries to it. Can you please test with a Python notebook?
